# Generated by Django 4.0.4 on 2022-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anonymous_query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
