# Generated by Django 4.1.2 on 2022-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0002_product_anonymous_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='anonymous_query',
            field=models.IntegerField(default=0),
        ),
    ]
